# Generated by Django 3.2.12 on 2022-02-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image_url', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image_url',
        ),
    ]
